# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ehREcPhPV_msvIrnCfuI0AiTIbR_fdQe
"""

import libreria as dios
dios.sumar(2,3)
dios.es_par_o_impar(3)
dios.saludar_usuario()
dios.calcular_area_circulo(2)
dios.clasificar_numero(2)
dios.celsius_a_fahrenheit(6)
dios.obtener_cuadrado(2)
dios.calcular_factorial(5)
dios.contar_vocales(palabra)

dios.mostrar_tabla_multiplicar(

)